version: "3.3"

volumes:
  dummy:

services:
  pipenv: &pipenv
    image: python:3.12-slim
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "dummy:/app/.venv"
    command: ["bash", "-c", "pip install pipenv && pipenv install --dev --deploy --system && pytest -s -vvv"]
  db: &db
    container_name: "sql_test_db"
    image: "mdillon/postgis:11"
    volumes:
      - "./sql:/sql"
    env_file:
      - "env/local/.env"
    ports:
      - "5438:5432"

  testdb:
    <<: *db
    container_name: "testdb"
    restart: "always"
    env_file:
      - "env/test/.env"
    ports:
      - "5432"


  dbtest:
    <<: *pipenv
    command: ["bash", "-c", "pip install pipenv && pipenv install --dev --deploy --system && pytest -s -vvv"]
    depends_on:
      - testdb
